services:
  - type: web
    name: rag-system
    env: python
    plan: starter
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    healthCheckPath: /health
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PORT
        value: 8000
      - key: LLM_PROVIDER
        value: gemini
      - key: LLM_MODEL
        value: gemini-1.5-flash
      - key: VECTOR_STORE_TYPE
        value: faiss
      - key: EMBEDDING_MODEL
        value: sentence-transformers/all-MiniLM-L6-v2
      - key: CHUNK_SIZE
        value: 500
      - key: CHUNK_OVERLAP
        value: 100
      - key: TOP_K
        value: 5
      - key: SIMILARITY_THRESHOLD
        value: 0.7
      - key: ENABLE_OCR
        value: true
      - key: ENABLE_METRICS
        value: false
      - key: DEBUG
        value: false
